### ISSUE TITLE
Attribute error for Gram matrices

### ISSUE THREAD

**Issue by adiaz20** [NEFM-TUDresden/MCRpy#4]
When I try to characterize a microstructure using the Gram matrices descriptor, the following error is raised: 
AttributeError: 'tuple' object has no attribute 'as_list'

I suspect that it could be caused by the deprecation of the tensorflow function to convert a keras tensor into a tf tensor, but I don't know how to solve that.

**Comment by s5409693** [comment]
Does the error still occur if you use exactly the versions listed in the table in https://github.com/NEFM-TUDresden/MCRpy#Dependencies (not newer versions but exactly these versions)?
